### ISSUE TITLE
Firmware 0.9.4.5 missing in repo

### ISSUE THREAD

**Issue by chuckhousley** [jakplugg/Neutron-Sound-Dust-of-Time#1]
The changelog in the firmwares directory has notes for v0.9.4.5 but the latest firmware in the directory is 0.9.0. Can the newer firmware be added to the repo?

Thanks

**Comment by jakplugg** [comment]
Sorry! Most of the intermediate test firmwares are uploaded to the "neutron sound dust of time building and firmware" Facebook group.

**Comment by chuckhousley** [comment]
Understood, closing the issue
