### ISSUE TITLE
Testing releases

### ISSUE THREAD

**Issue by lfwsound** [jakplugg/Neutron-Sound-Dust-of-Time#2]
Hi, could you please post the testing releases on Github for those that don't use FB? Or can you send the latest to me directly please? Thanks.

**Comment by s3kkt** [comment]
I have the same request. It's very sad to see the lack of activity here.

**Comment by lfwsound** [comment]
bump...please post the beta releases here too

**Comment by jakplugg** [comment]
I can't post them all, but I will try and post the last one if i do several in a few days.

**Comment by jakplugg** [comment]
0.9.6E has been uploaded

**Comment by lfwsound** [comment]
Great news. Thank you!
